#!/bin/sh
set -e

if which py3clean >/dev/null 2>&1; then
        py3clean -p python3-fand
else
        dpkg -L python3-fand | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
        find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

username="fand"
fand_service="/lib/systemd/system/fand.service"


case "$1" in remove|upgrade|deconfigure)

        if [ -L $fand_service ] || [ -f $fand_service ]
        then
            /bin/systemctl stop fand.service > /dev/null || true
            /bin/systemctl disable fand.service > /dev/null || true
            /bin/rm ${fand_service} > /dev/null || true
        fi

        if getent passwd ${username} >/dev/null;
          then
            echo "Delete user "${username}
            userdel -r ${username}
        fi

        ;;

        failed-upgrade)
        ;;

        *)
                echo "prerm called with unknown argument \`$1'" >&2
                exit 1
        ;;
esac

exit 0